[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.8.0"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[[bench]]
name = "searching"
harness = false

[profile.release]
codegen-units = 1

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = [
    "serde",
    "clock",
    "std",
], default-features = false }
clap = { version = "4.4", features = ["derive"] }
colored = "2.1"
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
git2 = "0.18"
human-panic = "1.2"
itertools = "0.12"
quork = "0.6"
rayon = "1.8"
regex = "1.10"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "./sfsu-derive" }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
url = { version = "2.5", features = ["serde"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
