[package]
description = "Stupid Fast Scoop Utils"
edition     = "2021"
name        = "sfsu"
version     = "1.8.7"

[workspace]
members = ["sfsu-derive"]

[[bench]]
harness = false
name    = "searching"

[profile.release]
codegen-units = 1
lto           = true

[features]
default        = ["info-difftrees", "v2"]
info-difftrees = []
# Breaking changes are locked behind this feature flag
v2 = []

[dependencies]
anyhow = "1.0"
cfg-if = "1.0.0"
chrono = { version = ">=0.4.20", features = [
    "clock",
    "serde",
    "std",
], default-features = false }
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
const-str = { version = "0.5", features = ["all"] }
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
git2 = "0.18"
human-panic = "1.2"
itertools = "0.12"
quork = "0.6"
rayon = "1.10"
regex = "1.10"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "./sfsu-derive" }
shadow-rs = "0.27"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
which = "6.0.1"

[dev-dependencies]
chrono    = ">=0.4.20"
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
shadow-rs = "0.27"
